DROP TABLE USER_INFO CASCADE constraints;

DROP TABLE LEVEL_INFO CASCADE constraints;

CREATE TABLE user_info(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    LEVELS_COMPLETED NUMBER,
    HAS_STARTED_GAME CHAR(1) CHECK (HAS_STARTED_GAME IN ('0', '1')),
    CONSTRAINT PK_EMAIL PRIMARY KEY (EMAIL)
);

CREATE TABLE level_info(
    EMAIL VARCHAR(50) NOT NULL,
    LEVEL_NUMBER NUMBER,
    SCORE NUMBER,
    TIME_TAKEN NUMBER,
    CONSTRAINT PK_EMAIL_AND_LEVEL PRIMARY KEY (EMAIL, LEVEL_NUMBER),
    CONSTRAINT FK_EMAIL FOREIGN KEY (EMAIL) REFERENCES USER_INFO ON DELETE CASCADE
);



DROP USER GAMEADMIN;

CREATE USER GAMEADMIN IDENTIFIED BY gameAdminpassword3;

GRANT SELECT, INSERT, UPDATE, DELETE ON USER_INFO TO GAMEADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON LEVEL_INFO TO GAMEADMIN;

GRANT CREATE SESSION TO GAMEADMIN;

GRANT CREATE TABLE TO GAMEADMIN;


alter user gameAdmin identified by gameAdminpassword3;
select * from user_info;
